favicon:
  mimetype: image/png
  path: themes/custom/aaslp_lib_unb_ca/favicon.png
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: ''
  use_default: false
