<?php

/**
* @file
* Contains aaslp_search.module.
*/

use Drupal\taxonomy\Entity\Term;

function aaslp_search_form_views_exposed_form_alter(&$form, &$form_state, $form_id){

  $view_id = $form['#id'];

  if (strpos($view_id, 'views-exposed-form-aaslp-metadata') === 0) {
    $tip = "Search by title, location, year, tags, abstract, or " .
      "combination, i.e. Jamaica 1800.";
  }
  elseif (strpos($view_id, 'views-exposed-form-aaslp-search') === 0) {
    $tip = "Search for keywords within the full text content of legal " .
      "articles.";
  }

  if (isset($form['search_api_fulltext']) and $tip) {
    $form['search_api_fulltext']['#description'] = t($tip);
  }
}

function aaslp_search_preprocess_facets_item_list(&$variables) {
  // Only apply to facet facet_full_location.
  $facets = [
    'facet_full_location',
    'metadata_location',
  ];

  if (in_array($variables['facet']->id(), $facets)) {
    // Get facet items and cycle through them.
    $items = $variables['items'];

    foreach ($items as $key => $item) {
      // Get taxonomy term ID for facet.
      $tid = $item['#title']['#raw_value'];
      $term = Term::load($tid);
      // Get ID for parent term.
      $parent = $term->parent->target_id ?? NULL;

      // If the term has a parent, add class child-location to wrapper.
      if ($parent == '0') {
        $variables['items'][$key]['#wrapper_attributes']['class'][]
          = 'parent-location';
      }
      else {
        $variables['items'][$key]['#wrapper_attributes']['class'][]
          = 'child-location';
      }
    }
  }
}
