<?php

/**
* @file
* Contains aaslp_search.module.
*/

use Drupal\taxonomy\Entity\Term;

function aaslp_search_form_views_exposed_form_alter(&$form, &$form_state, $form_id){

  $view_id = $form['#id'];

  if (strpos($view_id, 'views-exposed-form-aaslp-metadata') === 0) {
    $tip = "Search by title, location, year, tags, abstract, or " .
      "combination, i.e. Jamaica 1800.";
  }
  elseif (strpos($view_id, 'views-exposed-form-aaslp-search') === 0) {
    $tip = "Search for keywords within the full text content of legal " .
      "articles.";
  }

  if (isset($form['search_api_fulltext']) and $tip) {
    $form['search_api_fulltext']['#description'] = t($tip);
  }
}

function aaslp_search_preprocess_facets_item_list(&$variables) {
  // Only apply to facet facet_full_location.
  $facets = [
    'facet_full_location',
    'metadata_location',
  ];

  $parents = [];

  if (in_array($variables['facet']->id(), $facets)) {
    // Get facet items and cycle through them.
    $items = $variables['items'];

    foreach ($items as $key => $item) {
      // Get taxonomy term ID for facet.
      $tid = $item['#title']['#raw_value'];
      $term = Term::load($tid);

      // Get ID for parent term.
      $parent = $term->parent->target_id ?? NULL;

      // If the term has no parent, add class parent-location to wrapper.
      if (!$parent) {
        $variables['items'][$key]['#wrapper_attributes']['class'][]
          = 'parent-location';
        $variables['items'][$key]['#parent'] = $tid - 1;
      }
      else {
        $variables['items'][$key]['#wrapper_attributes']['class'][]
        = 'child-location';
        $variables['items'][$key]['#parent'] = $parent;
      }
    }
    
    $title = array_column($variables['items'], '#title');
    $name = array_column($title, '#count');
    $parents = array_column($variables['items'], '#parent');
    $count = array_column($title, '#count');
    array_multisort($parents, SORT_ASC, $count, SORT_DESC, $name, SORT_ASC, $variables['items']);
  }

}
