<?php

/**
* @file
* Contains legal_article.module.
*/

use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Entity;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function legal_article_node_presave($entity) {
  // Only apply to legal articles.
  if ($entity->bundle() == 'legal_article') {
    if (!empty($entity->field_location->getValue()[0]['target_id'])) {
      // Get location term ID.
      $lid = $entity->field_location->getValue()[0]['target_id'];
      // Load term if there is one.
      $lterm = !empty($lid) ? Term::load($lid) : NULL;
      // If location term found...
      if (!empty($lterm)) {
        // If location has a parent...
        if (!empty($lterm->parent->getValue())) {
          // Get parent location term ID and populate field.
          $lpid = $lterm->parent->getValue()[0]['target_id'];
          $entity->field_parent_location = $lpid;
        }
        // Otherwise use own location term id as parent.
        else {
          $entity->field_parent_location = $lid;
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function legal_article_theme($existing, $type, $theme, $path) {
  // Use custom template to display annotations field.
  $theme = [];

  $theme['field__field_annotations'] = [
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--node--field-annotations--legal-article',
    'path' => drupal_get_path('module', 'legal_article') . '/templates',
  ];

  $theme['field__field_editorial_annotations'] = [
    'render element' => 'content',
    'base hook' => 'field',
    'template' => 'field--node--field-editorial-annotations--legal-article',
    'path' => drupal_get_path('module', 'legal_article') . '/templates',
  ];

  return $theme;
}

/**
 * Implements hook_form_alter().
 */
function legal_article_form_alter(&$form, $form_state, $form_id) {
  // Hide revision switch field for legal article create/edit forms.
  if ($form_id == 'node_legal_article_form' or
    $form_id == 'node_legal_article_edit_form') {
    // For theme Seven (from Stable).
    $form['field_revision_switch']['#attributes']['class'][] = 'hidden';
    // For Bootstrap themes.
    $form['field_revision_switch']['#attributes']['class'][] = 'd-none';

    // Display only relevant fields if entering a timeline event.
    $show_field = [
      'visible' => [
        ':input[name*="field_timeline_event"]' => ['checked' => FALSE],
      ],
    ];

    $form['field_category']['#states'] =
      $form['field_citation']['#states'] =
      $form['field_crimes']['#states'] =
      $form['field_full_title']['#states'] =
      $form['field_location']['#states'] =
      $form['field_location_address']['#states'] =
      $form['field_location_coordinates']['#states'] =
      $form['field_notes']['#states'] =
      $form['field_source']['#states'] =
      $form['field_punishments']['#states'] =
      $show_field;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function legal_article_form_node_legal_article_edit_form_alter(&$form, $form_state, $form_id) {
  // Add submit handler to the top of the stack.
  array_unshift($form['actions']['submit']['#submit'], 'article_preprocess');;
}

function article_preprocess(&$form, $form_state) {
  // Flip field_revision_switch to force new revision on submit.
  $switch = $form_state->getValue('field_revision_switch')['value'];
  $form_state->setValue('field_revision_switch', ['value' => (int)!$switch]);
}
