<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
* @file
* Contains aaslp_core.module.
*/

/**
 * Implements hook_page_attachments().
 */
function aaslp_core_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'aaslp_core/homepage-active-tabs';
}

/**
 * Implements hook_form_alter().
 */
function aaslp_core_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  _fix_date_range($form);
}

/**
 * Recursively updates #date_year_range on all date elements.
 */
function _fix_date_range(array &$elements): void {
  foreach (Element::children($elements) as $key) {
    if (isset($elements[$key]['#type']) && in_array($elements[$key]['#type'], ['date', 'datetime', 'datelist'], TRUE)) {
      $elements[$key]['#date_year_range'] = '1500:2100';
    }
    _fix_date_range($elements[$key]);
  }
}