features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 0
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 1
b4_top_container: container
b4_body_schema: none
b4_body_bg_schema: none
b4_navbar_schema: dark
b4_navbar_bg_schema: none
b4_footer_schema: dark
b4_footer_bg_schema: none
subtheme_folder: themes/custom
subtheme_name: 'B4 subtheme'
subtheme_machine_name: b4subtheme
b4_top_container_config: ''
