sfl_recently_updated.settings:
  type: config_object
  label: 'sfl_recently_updated settings'
  mapping:
    langcode:
      type: string
      label: 'Language code'
    status:
      type: boolean
      label: 'Status'
    id:
      type: string
      label: 'Config ID'
    Label:
      type: string
      label: 'Human-readable label'
    module:
      type: string
      label: 'Module'
    description:
      type: string
      label: 'Description'
    core:
      type: string
      label: 'Drupal core compatibility'
    general:
      type: mapping
      label: 'General settings'
      mapping:
        text:
          type: string
          label: 'Text'